
#Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#Asteroid settings
ASTEROID_MIN_RADIUS = 10
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_TURN_SPEED = 300
ASTEROID_SPEED = 300
ASTEROID_ROTATION_SPEED = 120
ASTEROID_VERTICES = 8  # Number of vertices in asteroid shape
ASTEROID_IRREGULARITY = 0.4  # How irregular the shape can be (0-1)
ASTEROID_SMALL = 10
ASTEROID_MEDIUM = 20
ASTEROID_LARGE = 40

#Player settings
PLAYER_RADIUS = 20
PLAYER_ROTATION = 180
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

#Bullet settings
BULLET_SPEED = 500
BULLET_LIFETIME = 1 
BULLET_SIZE = 3

print(f"ASTEROID_LARGE = {ASTEROID_LARGE}")
print(f"ASTEROID_MEDIUM = {ASTEROID_MEDIUM}")
print(f"ASTEROID_SMALL = {ASTEROID_SMALL}")
print(f"ASTEROID_MIN_RADIUS = {ASTEROID_MIN_RADIUS}")